// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMH1yG-8je7ROa2qgR-F-AbJ5pjf2nLKM',
    appId: '1:821769277074:web:590f666c66c70f4eca204b',
    messagingSenderId: '821769277074',
    projectId: 'keeptruckin-bd438',
    authDomain: 'keeptruckin-bd438.firebaseapp.com',
    storageBucket: 'keeptruckin-bd438.appspot.com',
    measurementId: 'G-9V033NP9CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo5t5Y53brZEvwweuS-fTdloUdBtOil6A',
    appId: '1:821769277074:android:f8a31f2796333569ca204b',
    messagingSenderId: '821769277074',
    projectId: 'keeptruckin-bd438',
    storageBucket: 'keeptruckin-bd438.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4VS9G93vUTAOeoJk0Pzh47fJfZhrO-pU',
    appId: '1:821769277074:ios:a3f0f4d51540ccfcca204b',
    messagingSenderId: '821769277074',
    projectId: 'keeptruckin-bd438',
    storageBucket: 'keeptruckin-bd438.appspot.com',
    iosClientId: '821769277074-r8v566eju97pl7uqqt5kd7b7cfphuj3t.apps.googleusercontent.com',
    iosBundleId: 'com.v1ack.keeptruckin',
  );
}
